name: CI/CD

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: docker compose build

      - name: Run DB/Redis
        run: docker compose up -d db redis

      - name: Run tests
        env:
          # если твой проект падает без SECRET_KEY даже на тестах
          SECRET_KEY: test-secret-key
          DEBUG: "0"
        run: |
          docker compose run --rm web python manage.py test

      - name: Shutdown
        if: always()
        run: docker compose down -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # деплоим только из develop (под курсовую обычно так)
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            set -e
            cd ${{ secrets.PROJECT_DIR }}
            git fetch --all
            git reset --hard origin/develop



            docker compose -f docker-compose.prod.yml up -d --build
            docker compose -f docker-compose.prod.yml exec -T web python manage.py migrate
            docker compose -f docker-compose.prod.yml exec -T web python manage.py collect static --noinput || true